# Generated by Django 3.2.9 on 2021-11-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('admission_fee', models.FloatField()),
            ],
        ),
    ]
