# Generated by Django 3.2.9 on 2021-11-18 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_api', '0003_auto_20211117_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='national_park_api.nationalpark')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
