# Generated by Django 3.2.9 on 2021-11-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='NationalPark',
        ),
    ]
