# Generated by Django 3.2.9 on 2021-11-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_api', '0002_rename_contact_nationalpark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationalpark',
            options={'verbose_name': 'national_park', 'verbose_name_plural': 'national_park'},
        ),
        migrations.AddField(
            model_name='nationalpark',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
